In [1]:
import numpy as np
import matplotlib.pyplot as plt 
from sklearn import datasets
from sklearn.svm import SVC
from sklearn import preprocessing
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report
from sklearn.metrics import roc_curve, auc

In [2]:
data2 = np.genfromtxt("diabetes2.csv", delimiter=",", skip_header=1)
print data2
print data2.shape

[[   6.     148.      72.    ...,    0.627   50.       1.   ]
 [   1.      85.      66.    ...,    0.351   31.       0.   ]
 [   8.     183.      64.    ...,    0.672   32.       1.   ]
 ..., 
 [   5.     121.      72.    ...,    0.245   30.       0.   ]
 [   1.     126.      60.    ...,    0.349   47.       1.   ]
 [   1.      93.      70.    ...,    0.315   23.       0.   ]]
(768, 9)


In [3]:
dm_X = data2[:,:8]
print dm_X.shape
dm_y = data2[:,8]
print dm_y.shape

(768, 8)
(768,)


In [4]:
print np.unique(dm_y)

[ 0.  1.]


In [5]:
np.random.seed(0)
indices = np.random.permutation(len(dm_X))
num_train = int(.8*len(dm_X))
print num_train

dm_X_train = dm_X[indices[:num_train]]
dm_y_train = dm_y[indices[:num_train]]
dm_X_test = dm_X[indices[num_train:]]
dm_y_test = dm_y[indices[num_train:]] 
print dm_y_test
print dm_y_train

614
[ 0.  1.  0.  0.  1.  0.  0.  0.  0.  0.  1.  1.  1.  1.  0.  0.  1.  1.
  0.  0.  0.  1.  0.  0.  0.  1.  0.  0.  0.  0.  0.  0.  1.  1.  0.  0.
  0.  0.  0.  0.  1.  0.  0.  0.  0.  0.  0.  1.  1.  1.  0.  1.  0.  0.
  0.  0.  0.  0.  1.  1.  0.  1.  1.  0.  0.  1.  0.  0.  0.  1.  0.  1.
  0.  1.  0.  1.  0.  0.  0.  0.  1.  0.  0.  1.  0.  0.  0.  0.  0.  1.
  0.  1.  0.  0.  0.  0.  0.  1.  0.  0.  0.  0.  1.  0.  1.  0.  0.  0.
  1.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  1.  1.  1.  1.  0.
  1.  1.  1.  0.  0.  1.  0.  0.  0.  0.  0.  1.  0.  0.  0.  1.  0.  1.
  0.  0.  1.  1.  0.  0.  1.  0.  0.  0.]
[ 1.  0.  0.  1.  0.  0.  1.  1.  0.  0.  1.  1.  0.  0.  0.  0.  1.  0.
  0.  0.  1.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  1.
  1.  0.  0.  0.  0.  0.  0.  1.  1.  0.  0.  1.  1.  1.  0.  0.  1.  0.
  0.  0.  0.  1.  1.  1.  1.  0.  0.  1.  1.  1.  1.  0.  0.  0.  0.  0.
  0.  0.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  1.  0.  1.  0.
  0. 

In [6]:
min_max_scaler = preprocessing.MinMaxScaler()
dm_X_train_minmax = min_max_scaler.fit_transform(dm_X_train)
dm_X_test_minmax = min_max_scaler.transform(dm_X_test)
print dm_X_train_minmax
print dm_X_test_minmax

[[ 0.05882353  1.          0.62295082 ...,  0.72222222  0.56191289
   0.01960784]
 [ 0.11764706  0.53768844  0.60655738 ...,  0.56565657  0.13919727
   0.03921569]
 [ 0.23529412  0.38190955  0.50819672 ...,  0.57239057  0.13364646
   0.07843137]
 ..., 
 [ 0.11764706  0.45226131  0.57377049 ...,  0.45959596  0.0029889
   0.01960784]
 [ 0.52941176  0.7839196   0.70491803 ...,  0.57744108  0.47438087
   0.41176471]
 [ 0.          0.5879397   0.54098361 ...,  0.51851852  0.17719898
   0.01960784]]
[[ 0.05882353  0.35678392  0.50819672 ...,  0.36700337  0.14432109
   0.09803922]
 [ 0.05882353  0.86934673  0.60655738 ...,  0.61952862  0.00426985
   0.33333333]
 [ 0.29411765  0.52763819  0.59016393 ...,  0.62121212  0.03458582
   0.1372549 ]
 ..., 
 [ 0.23529412  0.47236181  0.53278689 ...,  0.41582492  0.02988898  0.        ]
 [ 0.64705882  0.42713568  0.60655738 ...,  0.50673401  0.09479078
   0.2745098 ]
 [ 0.29411765  0.68341709  0.67213115 ...,  0.          0.23996584
   0.94117647]]


In [7]:
svc = SVC(C=1.0, kernel='rbf', gamma = 0.01)
clf = svc.fit(dm_X_train_minmax, dm_y_train)
target = dm_y_test
prediction = svc.predict(dm_X_test_minmax)
print target.shape
print prediction.shape

accuracy = accuracy_score(target, prediction) 
print "accuracy: ", accuracy

cm = confusion_matrix(target, prediction) 
print "confusion matrix: \n", cm

report = classification_report(target, prediction) 
print "classification_report: \n", report

(154,)
(154,)
accuracy:  0.681818181818
confusion matrix: 
[[105   0]
 [ 49   0]]
classification_report: 
             precision    recall  f1-score   support

        0.0       0.68      1.00      0.81       105
        1.0       0.00      0.00      0.00        49

avg / total       0.46      0.68      0.55       154



/Users/LittleBird/Library/Enthought/Canopy_64bit/User/lib/python2.7/site-packages/sklearn/metrics/classification.py:1113: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples.
  'precision', 'predicted', average, warn_for)


In [8]:
svc = SVC(C=1.0, kernel='rbf', gamma = 0.01)
clf = svc.fit(dm_X_train, dm_y_train)
target = dm_y_test
prediction = svc.predict(dm_X_test)
accuracy = accuracy_score(target, prediction) 
print "accuracy: ", accuracy

cm = confusion_matrix(target, prediction) 
print "confusion matrix: \n", cm

report = classification_report(target, prediction) 
print "classification_report: \n", report

accuracy:  0.688311688312
confusion matrix: 
[[99  6]
 [42  7]]
classification_report: 
             precision    recall  f1-score   support

        0.0       0.70      0.94      0.80       105
        1.0       0.54      0.14      0.23        49

avg / total       0.65      0.69      0.62       154



In [9]:
svc = SVC(C=100.0, kernel='rbf', gamma = 0.01)
clf = svc.fit(dm_X_train_minmax, dm_y_train)
target = dm_y_test
prediction = svc.predict(dm_X_test_minmax)
print target.shape
print prediction.shape

accuracy = accuracy_score(target, prediction) 
print "accuracy: ", accuracy

cm = confusion_matrix(target, prediction) 
print "confusion matrix: \n", cm

report = classification_report(target, prediction) 
print "classification_report: \n", report

(154,)
(154,)
accuracy:  0.766233766234
confusion matrix: 
[[93 12]
 [24 25]]
classification_report: 
             precision    recall  f1-score   support

        0.0       0.79      0.89      0.84       105
        1.0       0.68      0.51      0.58        49

avg / total       0.76      0.77      0.76       154



In [10]:
svc = SVC(C=100.0, kernel='rbf', gamma = 0.01)
clf = svc.fit(dm_X_train, dm_y_train)
target = dm_y_test
prediction = svc.predict(dm_X_test)
accuracy = accuracy_score(target, prediction)  
print "accuracy: ", accuracy

cm = confusion_matrix(target, prediction) 
print "confusion matrix: \n", cm

report = classification_report(target, prediction) 
print "classification_report: \n", report

accuracy:  0.681818181818
confusion matrix: 
[[95 10]
 [39 10]]
classification_report: 
             precision    recall  f1-score   support

        0.0       0.71      0.90      0.79       105
        1.0       0.50      0.20      0.29        49

avg / total       0.64      0.68      0.63       154



In [11]:
svc = SVC(C=1.0, kernel='rbf', gamma = 0.125)
clf = svc.fit(dm_X_train_minmax, dm_y_train)
target = dm_y_test
prediction = svc.predict(dm_X_test_minmax)
print target.shape
print prediction.shape

accuracy = accuracy_score(target, prediction) 
print "accuracy: ", accuracy

cm = confusion_matrix(target, prediction) 
print "confusion matrix: \n", cm

report = classification_report(target, prediction) 
print "classification_report: \n", report

(154,)
(154,)
accuracy:  0.74025974026
confusion matrix: 
[[92 13]
 [27 22]]
classification_report: 
             precision    recall  f1-score   support

        0.0       0.77      0.88      0.82       105
        1.0       0.63      0.45      0.52        49

avg / total       0.73      0.74      0.73       154



In [12]:
svc = SVC(C=1.0, kernel='rbf', gamma = 0.125)
clf = svc.fit(dm_X_train, dm_y_train)
target = dm_y_test
prediction = svc.predict(dm_X_test)
accuracy = accuracy_score(target, prediction)  
print "accuracy: ", accuracy

cm = confusion_matrix(target, prediction) 
print "confusion matrix: \n", cm

report = classification_report(target, prediction) 
print "classification_report: \n", report

accuracy:  0.681818181818
confusion matrix: 
[[105   0]
 [ 49   0]]
classification_report: 
             precision    recall  f1-score   support

        0.0       0.68      1.00      0.81       105
        1.0       0.00      0.00      0.00        49

avg / total       0.46      0.68      0.55       154



In [25]:
svc = SVC(C=100.0, kernel='rbf', gamma = 0.125)
clf = svc.fit(dm_X_train_minmax, dm_y_train)
target = dm_y_test
prediction = svc.predict(dm_X_test_minmax)
print target.shape
print prediction.shape

accuracy = accuracy_score(target, prediction) 
print "accuracy: ", accuracy

cm = confusion_matrix(target, prediction) 
print "confusion matrix: \n", cm

report = classification_report(target, prediction) 
print "classification_report: \n", report

(154,)
(154,)
accuracy:  0.785714285714
confusion matrix: 
[[94 11]
 [22 27]]
classification_report: 
             precision    recall  f1-score   support

        0.0       0.81      0.90      0.85       105
        1.0       0.71      0.55      0.62        49

avg / total       0.78      0.79      0.78       154



In [17]:
svc = SVC(C=100.0, kernel='rbf', gamma = 0.125)
clf = svc.fit(dm_X_train, dm_y_train)
target = dm_y_test
prediction = svc.predict(dm_X_test)
accuracy = accuracy_score(target, prediction)  
print "accuracy: ", accuracy

cm = confusion_matrix(target, prediction) 
print "confusion matrix: \n", cm

report = classification_report(target, prediction) 
print "classification_report: \n", report

accuracy:  0.681818181818
confusion matrix: 
[[105   0]
 [ 49   0]]
classification_report: 
             precision    recall  f1-score   support

        0.0       0.68      1.00      0.81       105
        1.0       0.00      0.00      0.00        49

avg / total       0.46      0.68      0.55       154



In [18]:
svc = SVC(C=1.0, kernel='poly', degree=1)
clf = svc.fit(dm_X_train_minmax, dm_y_train)
target = dm_y_test
prediction = svc.predict(dm_X_test_minmax)
print target.shape
print prediction.shape

accuracy = accuracy_score(target, prediction) 
print "accuracy: ", accuracy

cm = confusion_matrix(target, prediction) 
print "confusion matrix: \n", cm

report = classification_report(target, prediction) 
print "classification_report: \n", report

(154,)
(154,)
accuracy:  0.733766233766
confusion matrix: 
[[98  7]
 [34 15]]
classification_report: 
             precision    recall  f1-score   support

        0.0       0.74      0.93      0.83       105
        1.0       0.68      0.31      0.42        49

avg / total       0.72      0.73      0.70       154



In [19]:
svc = SVC(C=1.0, kernel='poly', degree=1)
clf = svc.fit(dm_X_train, dm_y_train)
target = dm_y_test
prediction = svc.predict(dm_X_test)

accuracy = accuracy_score(target, prediction) 
print "accuracy: ", accuracy

cm = confusion_matrix(target, prediction) 
print "confusion matrix: \n", cm

report = classification_report(target, prediction) 
print "classification_report: \n", report

accuracy:  0.779220779221
confusion matrix: 
[[92 13]
 [21 28]]
classification_report: 
             precision    recall  f1-score   support

        0.0       0.81      0.88      0.84       105
        1.0       0.68      0.57      0.62        49

avg / total       0.77      0.78      0.77       154



In [20]:
svc = SVC(C=100.0, kernel='poly', degree=1)
clf = svc.fit(dm_X_train_minmax, dm_y_train)
target = dm_y_test
prediction = svc.predict(dm_X_test_minmax)
print target.shape
print prediction.shape

accuracy = accuracy_score(target, prediction) 
print "accuracy: ", accuracy

cm = confusion_matrix(target, prediction) 
print "confusion matrix: \n", cm

report = classification_report(target, prediction) 
print "classification_report: \n", report

(154,)
(154,)
accuracy:  0.772727272727
confusion matrix: 
[[92 13]
 [22 27]]
classification_report: 
             precision    recall  f1-score   support

        0.0       0.81      0.88      0.84       105
        1.0       0.68      0.55      0.61        49

avg / total       0.77      0.77      0.77       154



In [21]:
svc = SVC(C=100.0, kernel='poly', degree=1)
clf = svc.fit(dm_X_train, dm_y_train)
target = dm_y_test
prediction = svc.predict(dm_X_test)
accuracy = accuracy_score(target, prediction) 
print "accuracy: ", accuracy

cm = confusion_matrix(target, prediction) 
print "confusion matrix: \n", cm

report = classification_report(target, prediction) 
print "classification_report: \n", report

accuracy:  0.772727272727
confusion matrix: 
[[91 14]
 [21 28]]
classification_report: 
             precision    recall  f1-score   support

        0.0       0.81      0.87      0.84       105
        1.0       0.67      0.57      0.62        49

avg / total       0.77      0.77      0.77       154



In [22]:
svc = SVC(C=1.0, kernel='poly', degree=2)
clf = svc.fit(dm_X_train_minmax, dm_y_train)
target = dm_y_test
prediction = svc.predict(dm_X_test_minmax)
print target.shape
print prediction.shape

accuracy = accuracy_score(target, prediction) 
print "accuracy: ", accuracy

cm = confusion_matrix(target, prediction) 
print "confusion matrix: \n", cm

report = classification_report(target, prediction) 
print "classification_report: \n", report

(154,)
(154,)
accuracy:  0.707792207792
confusion matrix: 
[[105   0]
 [ 45   4]]
classification_report: 
             precision    recall  f1-score   support

        0.0       0.70      1.00      0.82       105
        1.0       1.00      0.08      0.15        49

avg / total       0.80      0.71      0.61       154



In [23]:
svc = SVC(C=1.0, kernel='poly', degree=2)
clf = svc.fit(dm_X_train, dm_y_train)
target = dm_y_test
prediction = svc.predict(dm_X_test)
accuracy = accuracy_score(target, prediction) 
print "accuracy: ", accuracy

cm = confusion_matrix(target, prediction) 
print "confusion matrix: \n", cm

report = classification_report(target, prediction) 
print "classification_report: \n", report

accuracy:  0.688311688312
confusion matrix: 
[[80 25]
 [23 26]]
classification_report: 
             precision    recall  f1-score   support

        0.0       0.78      0.76      0.77       105
        1.0       0.51      0.53      0.52        49

avg / total       0.69      0.69      0.69       154



In [26]:
svc = SVC(C=100.0, kernel='poly', degree=2)
clf = svc.fit(dm_X_train_minmax, dm_y_train)
target = dm_y_test
prediction_best = svc.predict(dm_X_test_minmax)
pred_best = svc.decision_function(dm_X_test_minmax)
print target.shape
print prediction.shape

accuracy = accuracy_score(target, prediction_best) 
print "accuracy: ", accuracy

cm = confusion_matrix(target, prediction_best) 
print "confusion matrix: \n", cm

report = classification_report(target, prediction_best) 
print "classification_report: \n", report

(154,)
(154,)
accuracy:  0.798701298701
confusion matrix: 
[[95 10]
 [21 28]]
classification_report: 
             precision    recall  f1-score   support

        0.0       0.82      0.90      0.86       105
        1.0       0.74      0.57      0.64        49

avg / total       0.79      0.80      0.79       154



In [27]:
svc = SVC(C=100.0, kernel='poly', degree=2)
clf = svc.fit(dm_X_train, dm_y_train)
target = dm_y_test
prediction = svc.predict(dm_X_test)
accuracy = accuracy_score(target, prediction)
print "accuracy: ", accuracy

cm = confusion_matrix(target, prediction) 
print "confusion matrix: \n", cm

report = classification_report(target, prediction) 
print "classification_report: \n", report

accuracy:  0.662337662338
confusion matrix: 
[[78 27]
 [25 24]]
classification_report: 
             precision    recall  f1-score   support

        0.0       0.76      0.74      0.75       105
        1.0       0.47      0.49      0.48        49

avg / total       0.67      0.66      0.66       154



In [28]:
fpr, tpr, thresholds = roc_curve(target, pred_best)
print thresholds
roc_auc = auc(fpr, tpr) 
print "Area under the ROC curve : %f" % roc_auc

[ 2.49976906  1.41222838  1.26879395  1.20214334  1.17012635  0.87568731
  0.86739186  0.74105983  0.65596716  0.58539506  0.5097528   0.41969818
  0.37771531  0.352314    0.30827177 -0.04648777 -0.39199216 -0.51926911
 -0.57791021 -0.58555964 -0.70972178 -0.71602447 -0.78356684 -0.88860128
 -0.90018665 -0.91149973 -0.99411655 -0.99559765 -1.06556169 -1.06811582
 -1.11769369 -1.12363463 -1.33226254 -1.34223389 -1.39314648 -1.39716075
 -1.44231479 -1.48796117 -2.17471606 -2.18452553 -3.09805372]
Area under the ROC curve : 0.815160


In [29]:
plt.figure()
plt.plot(fpr, tpr, label='ROC curve (area = %0.2f)' % roc_auc, lw=4, color ="#0000ff", marker='s',markerfacecolor="red")
plt.plot([0, 1], [0, 1], 'k--')
plt.xlim([-0.005, 1.0])
plt.ylim([0.0, 1.005])
plt.xlabel('False Positive Rate (1-specificity)') 
plt.ylabel('True Positive Rate (sensitivity)') 
plt.title('ROC curve')
plt.legend(loc="lower right") 
plt.show()

In [30]:
fig, axes = plt.subplots(nrows=1, ncols=2)

dm_X1 = data2[:,0]
dm_X2 = data2[:,4]

axes[0].scatter(dm_X1, dm_y, alpha=.5, color='blue')
axes[0].set_xlabel('Number of Times Pregnant')
axes[0].set_ylabel('Diabetes')
axes[0].set_title('Scatter Diagram for Diabetes vs Gravidity')

axes[1].scatter(dm_X2, dm_y, alpha=.5, color='red')
axes[1].set_xlabel('2-Hour Serum Insulin Level')
axes[1].set_ylabel('Diabetes')
axes[1].set_title('Scatter Diagram for Diabetes vs Insulin Level')

plt.show()